   
addArquero:
    path:   /Arquero/add
    defaults: { _controller: PersonaBundle:Arquero:Add}
queryArquero:
    path:   /Arquero/query
    defaults: { _controller: PersonaBundle:Arquero:Query}
editArquero:
    path:   /Arquero/edit/{id}
    defaults: { _controller: PersonaBundle:Arquero:Edit}
deleteArquero:
    path:   /Arquero/delete/{id}
    defaults: { _controller: PersonaBundle:Arquero:Delete}

addPersona:
    path:   /Persona/add
    defaults: { _controller: PersonaBundle:Persona:Add}
queryPersona:
    path:   /Persona/query
    defaults: { _controller: PersonaBundle:Persona:Query}
editPersona:
    path:   /Persona/edit/{id}
    defaults: { _controller: PersonaBundle:Persona:Edit}
deletePersona:
    path:   /Persona/delete/{id}
    defaults: { _controller: PersonaBundle:Persona:Delete}
    
persona_homepage:
    path:    /Persona
    defaults: { _controller: PersonaBundle:Persona:index }
